<?php
include 'includes/db_connect.php';

if (!isset($_GET['id'])) {
    die("Invalid Request");
}

$id = $_GET['id'];
$stmt = $pdo->prepare("SELECT a.*, d.doc_name, s.spec_name 
                       FROM appointments a 
                       JOIN doctors d ON a.doctor_id = d.id 
                       JOIN specialties s ON d.specialty_id = s.id 
                       WHERE a.id = ?");
$stmt->execute([$id]);
$app = $stmt->fetch();

if (!$app) { die("Appointment not found"); }
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Appointment Slip - <?php echo $app['patient_name']; ?></title>
    <style>
        body { font-family: 'Inter', sans-serif; color: #333; background: #f4f7f6; padding: 20px; }
        .slip-card { 
            max-width: 500px; margin: 0 auto; background: white; 
            border: 2px solid #0061f2; border-radius: 15px; overflow: hidden;
            box-shadow: 0 10px 25px rgba(0,0,0,0.1);
        }
        .header { background: #0061f2; color: white; padding: 20px; text-align: center; }
        .content { padding: 30px; }
        .row { display: flex; justify-content: space-between; margin-bottom: 15px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        .label { font-weight: bold; color: #666; font-size: 0.9rem; }
        .value { font-weight: 700; text-align: right; }
        .emergency-badge { background: #e53e3e; color: white; padding: 5px 10px; border-radius: 5px; font-size: 0.8rem; }
        .footer { text-align: center; padding: 20px; font-size: 0.8rem; color: #999; }
        .btn-print { 
            display: block; width: 100%; max-width: 200px; margin: 20px auto; 
            padding: 10px; background: #0061f2; color: white; border: none; 
            border-radius: 5px; cursor: pointer; font-weight: bold;
        }
        @media print { .btn-print { display: none; } body { background: white; padding: 0; } .slip-card { box-shadow: none; border: 1px solid #ccc; } }
    </style>
</head>
<body>

<div class="slip-card">
    <div class="header">
        <h2 style="margin:0;">SwiftCare</h2>
        <p style="margin:5px 0 0; opacity: 0.8;">Official Appointment Slip</p>
    </div>
    <div class="content">
        <div style="text-align:center; margin-bottom: 20px;">
            <?php if($app['is_emergency']): ?>
                <span class="emergency-badge">PRIORITY EMERGENCY</span>
            <?php endif; ?>
        </div>

        <div class="row">
            <span class="label">Token ID:</span>
            <span class="value">#SC-<?php echo $app['id'] . date('Y'); ?></span>
        </div>
        <div class="row">
            <span class="label">Patient:</span>
            <span class="value"><?php echo htmlspecialchars($app['patient_name']); ?></span>
        </div>
        <div class="row">
            <span class="label">Doctor:</span>
            <span class="value"><?php echo $app['doc_name']; ?> (<?php echo $app['spec_name']; ?>)</span>
        </div>
        <div class="row">
            <span class="label">Date:</span>
            <span class="value"><?php echo date('D, M j, Y', strtotime($app['appointment_date'])); ?></span>
        </div>
        <div class="row">
            <span class="label">Time:</span>
            <span class="value"><?php echo date('h:i A', strtotime($app['appointment_time'])); ?></span>
        </div>
        <div class="row">
            <span class="label">Service:</span>
            <span class="value"><?php echo $app['tier']; ?> - <?php echo $app['service_type']; ?></span>
        </div>
        
        <?php if($app['home_address']): ?>
        <div class="row" style="flex-direction: column; border: none;">
            <span class="label">Delivery Address:</span>
            <span class="value" style="text-align: left; margin-top: 5px; font-size: 0.85rem;"><?php echo htmlspecialchars($app['home_address']); ?></span>
        </div>
        <?php endif; ?>
    </div>
    <div class="footer">
        Generated by SwiftCare Management System<br>
        Please present this slip upon arrival.
    </div>
</div>

<button class="btn-print" onclick="window.print()">Print Appointment Slip</button>

</body>
</html>